// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC-upIkpeCEpJ6ZSikQfVr1UybDwGr_SFA',
    appId: '1:100034309299:web:e169a89d899619b72194c6',
    messagingSenderId: '100034309299',
    projectId: 'app-despensas-db',
    authDomain: 'app-despensas-db.firebaseapp.com',
    storageBucket: 'app-despensas-db.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAOZO2viapMfTEwwgchX6ZVKW89Lab6-gg',
    appId: '1:100034309299:android:775d881c57d5a1e02194c6',
    messagingSenderId: '100034309299',
    projectId: 'app-despensas-db',
    storageBucket: 'app-despensas-db.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCNSggiGzY5mpg0usQjW8KXAig88I0j37s',
    appId: '1:100034309299:ios:414396b9a82648a42194c6',
    messagingSenderId: '100034309299',
    projectId: 'app-despensas-db',
    storageBucket: 'app-despensas-db.appspot.com',
    iosBundleId: 'com.example.appDespensas',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCNSggiGzY5mpg0usQjW8KXAig88I0j37s',
    appId: '1:100034309299:ios:414396b9a82648a42194c6',
    messagingSenderId: '100034309299',
    projectId: 'app-despensas-db',
    storageBucket: 'app-despensas-db.appspot.com',
    iosBundleId: 'com.example.appDespensas',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC-upIkpeCEpJ6ZSikQfVr1UybDwGr_SFA',
    appId: '1:100034309299:web:fb2cf3b59af212362194c6',
    messagingSenderId: '100034309299',
    projectId: 'app-despensas-db',
    authDomain: 'app-despensas-db.firebaseapp.com',
    storageBucket: 'app-despensas-db.appspot.com',
  );
}
